// videosData.js
export const videosData = [
  {
    id: 1,
    videoUrl: "https://res.cloudinary.com/drrj8rl9n/video/upload/v1757175304/Rim_Jhim_-_Khan_Saab_ft._Pav_Dharia_PunjabiSong_Fresh_Media_Records_p1ugsf.mp4",
    thumbnailUrl: "https://res.cloudinary.com/drrj8rl9n/image/upload/v1757177217/Screenshot_2025-09-06_221531_ku9pfb.png",
    avatar: "https://randomuser.me/api/portraits/men/32.jpg",
    title: "Rim Jhim - Khan Saab ft. Pav Dharia",
    channelName: "Fresh Media Records",
    views: "2.3M",
    timeAgo: "1 year ago",
  },
  {
    id: 2,
    videoUrl: "https://res.cloudinary.com/drrj8rl9n/video/upload/v1755250102/samples/dance-2.mp4",
    thumbnailUrl: "https://res.cloudinary.com/drrj8rl9n/image/upload/v1757175188/Grand_Theft_Auto_V_Enhanced_5_17_2025_10_23_02_PM_iwux6w.png",
    avatar: "https://randomuser.me/api/portraits/women/44.jpg",
    title: "Sample Music Video",
    channelName: "Demo Channel",
    views: "450K",
    timeAgo: "3 months ago",
  },
  {
    id: 3,
    videoUrl: "https://res.cloudinary.com/drrj8rl9n/video/upload/v1757175304/Rim_Jhim_-_Khan_Saab_ft._Pav_Dharia_PunjabiSong_Fresh_Media_Records_p1ugsf.mp4",
    thumbnailUrl: "https://res.cloudinary.com/drrj8rl9n/image/upload/v1755250102/cld-sample-4.jpg",
    avatar: "https://randomuser.me/api/portraits/men/77.jpg",
    title: "Cute Dog Video Compilation",
    channelName: "Animal Planet",
    views: "1.1M",
    timeAgo: "2 weeks ago",
  },
  {
    id: 1,
    videoUrl: "https://res.cloudinary.com/drrj8rl9n/video/upload/v1757175304/Rim_Jhim_-_Khan_Saab_ft._Pav_Dharia_PunjabiSong_Fresh_Media_Records_p1ugsf.mp4",
    thumbnailUrl: "https://res.cloudinary.com/drrj8rl9n/image/upload/v1757177217/Screenshot_2025-09-06_221531_ku9pfb.png",
    avatar: "https://randomuser.me/api/portraits/men/32.jpg",
    title: "Rim Jhim - Khan Saab ft. Pav Dharia",
    channelName: "Fresh Media Records",
    views: "2.3M",
    timeAgo: "1 year ago",
  },
  {
    id: 2,
    videoUrl: "https://res.cloudinary.com/drrj8rl9n/video/upload/v1755250102/samples/dance-2.mp4",
    thumbnailUrl: "https://res.cloudinary.com/drrj8rl9n/image/upload/v1757175188/Grand_Theft_Auto_V_Enhanced_5_17_2025_10_23_02_PM_iwux6w.png",
    avatar: "https://randomuser.me/api/portraits/women/44.jpg",
    title: "Sample Music Video",
    channelName: "Demo Channel",
    views: "450K",
    timeAgo: "3 months ago",
  },
  {
    id: 3,
    videoUrl: "https://res.cloudinary.com/drrj8rl9n/video/upload/v1757175304/Rim_Jhim_-_Khan_Saab_ft._Pav_Dharia_PunjabiSong_Fresh_Media_Records_p1ugsf.mp4",
    thumbnailUrl: "https://res.cloudinary.com/drrj8rl9n/image/upload/v1755250102/cld-sample-4.jpg",
    avatar: "https://randomuser.me/api/portraits/men/77.jpg",
    title: "Cute Dog Video Compilation",
    channelName: "Animal Planet",
    views: "1.1M",
    timeAgo: "2 weeks ago",
  },{
    id: 1,
    videoUrl: "https://res.cloudinary.com/drrj8rl9n/video/upload/v1757175304/Rim_Jhim_-_Khan_Saab_ft._Pav_Dharia_PunjabiSong_Fresh_Media_Records_p1ugsf.mp4",
    thumbnailUrl: "https://res.cloudinary.com/drrj8rl9n/image/upload/v1757177217/Screenshot_2025-09-06_221531_ku9pfb.png",
    avatar: "https://randomuser.me/api/portraits/men/32.jpg",
    title: "Rim Jhim - Khan Saab ft. Pav Dharia",
    channelName: "Fresh Media Records",
    views: "2.3M",
    timeAgo: "1 year ago",
  },
  {
    id: 2,
    videoUrl: "https://res.cloudinary.com/drrj8rl9n/video/upload/v1755250102/samples/dance-2.mp4",
    thumbnailUrl: "https://res.cloudinary.com/drrj8rl9n/image/upload/v1757175188/Grand_Theft_Auto_V_Enhanced_5_17_2025_10_23_02_PM_iwux6w.png",
    avatar: "https://randomuser.me/api/portraits/women/44.jpg",
    title: "Sample Music Video",
    channelName: "Demo Channel",
    views: "450K",
    timeAgo: "3 months ago",
  },
  {
    id: 3,
    videoUrl: "https://res.cloudinary.com/drrj8rl9n/video/upload/v1757175304/Rim_Jhim_-_Khan_Saab_ft._Pav_Dharia_PunjabiSong_Fresh_Media_Records_p1ugsf.mp4",
    thumbnailUrl: "https://res.cloudinary.com/drrj8rl9n/image/upload/v1755250102/cld-sample-4.jpg",
    avatar: "https://randomuser.me/api/portraits/men/77.jpg",
    title: "Cute Dog Video Compilation",
    channelName: "Animal Planet",
    views: "1.1M",
    timeAgo: "2 weeks ago",
  },{
    id: 1,
    videoUrl: "https://res.cloudinary.com/drrj8rl9n/video/upload/v1757175304/Rim_Jhim_-_Khan_Saab_ft._Pav_Dharia_PunjabiSong_Fresh_Media_Records_p1ugsf.mp4",
    thumbnailUrl: "https://res.cloudinary.com/drrj8rl9n/image/upload/v1757177217/Screenshot_2025-09-06_221531_ku9pfb.png",
    avatar: "https://randomuser.me/api/portraits/men/32.jpg",
    title: "Rim Jhim - Khan Saab ft. Pav Dharia",
    channelName: "Fresh Media Records",
    views: "2.3M",
    timeAgo: "1 year ago",
  },
  {
    id: 2,
    videoUrl: "https://res.cloudinary.com/drrj8rl9n/video/upload/v1755250102/samples/dance-2.mp4",
    thumbnailUrl: "https://res.cloudinary.com/drrj8rl9n/image/upload/v1757175188/Grand_Theft_Auto_V_Enhanced_5_17_2025_10_23_02_PM_iwux6w.png",
    avatar: "https://randomuser.me/api/portraits/women/44.jpg",
    title: "Sample Music Video",
    channelName: "Demo Channel",
    views: "450K",
    timeAgo: "3 months ago",
  },
  {
    id: 3,
    videoUrl: "https://res.cloudinary.com/drrj8rl9n/video/upload/v1757175304/Rim_Jhim_-_Khan_Saab_ft._Pav_Dharia_PunjabiSong_Fresh_Media_Records_p1ugsf.mp4",
    thumbnailUrl: "https://res.cloudinary.com/drrj8rl9n/image/upload/v1755250102/cld-sample-4.jpg",
    avatar: "https://randomuser.me/api/portraits/men/77.jpg",
    title: "Cute Dog Video Compilation",
    channelName: "Animal Planet",
    views: "1.1M",
    timeAgo: "2 weeks ago",
  },{
    id: 1,
    videoUrl: "https://res.cloudinary.com/drrj8rl9n/video/upload/v1757175304/Rim_Jhim_-_Khan_Saab_ft._Pav_Dharia_PunjabiSong_Fresh_Media_Records_p1ugsf.mp4",
    thumbnailUrl: "https://res.cloudinary.com/drrj8rl9n/image/upload/v1757177217/Screenshot_2025-09-06_221531_ku9pfb.png",
    avatar: "https://randomuser.me/api/portraits/men/32.jpg",
    title: "Rim Jhim - Khan Saab ft. Pav Dharia",
    channelName: "Fresh Media Records",
    views: "2.3M",
    timeAgo: "1 year ago",
  },
  {
    id: 2,
    videoUrl: "https://res.cloudinary.com/drrj8rl9n/video/upload/v1755250102/samples/dance-2.mp4",
    thumbnailUrl: "https://res.cloudinary.com/drrj8rl9n/image/upload/v1757175188/Grand_Theft_Auto_V_Enhanced_5_17_2025_10_23_02_PM_iwux6w.png",
    avatar: "https://randomuser.me/api/portraits/women/44.jpg",
    title: "Sample Music Video",
    channelName: "Demo Channel",
    views: "450K",
    timeAgo: "3 months ago",
  },
  {
    id: 3,
    videoUrl: "https://res.cloudinary.com/drrj8rl9n/video/upload/v1757175304/Rim_Jhim_-_Khan_Saab_ft._Pav_Dharia_PunjabiSong_Fresh_Media_Records_p1ugsf.mp4",
    thumbnailUrl: "https://res.cloudinary.com/drrj8rl9n/image/upload/v1755250102/cld-sample-4.jpg",
    avatar: "https://randomuser.me/api/portraits/men/77.jpg",
    title: "Cute Dog Video Compilation",
    channelName: "Animal Planet",
    views: "1.1M",
    timeAgo: "2 weeks ago",
  },{
    id: 1,
    videoUrl: "https://res.cloudinary.com/drrj8rl9n/video/upload/v1757175304/Rim_Jhim_-_Khan_Saab_ft._Pav_Dharia_PunjabiSong_Fresh_Media_Records_p1ugsf.mp4",
    thumbnailUrl: "https://res.cloudinary.com/drrj8rl9n/image/upload/v1757177217/Screenshot_2025-09-06_221531_ku9pfb.png",
    avatar: "https://randomuser.me/api/portraits/men/32.jpg",
    title: "Rim Jhim - Khan Saab ft. Pav Dharia",
    channelName: "Fresh Media Records",
    views: "2.3M",
    timeAgo: "1 year ago",
  },
  {
    id: 2,
    videoUrl: "https://res.cloudinary.com/drrj8rl9n/video/upload/v1755250102/samples/dance-2.mp4",
    thumbnailUrl: "https://res.cloudinary.com/drrj8rl9n/image/upload/v1757175188/Grand_Theft_Auto_V_Enhanced_5_17_2025_10_23_02_PM_iwux6w.png",
    avatar: "https://randomuser.me/api/portraits/women/44.jpg",
    title: "Sample Music Video",
    channelName: "Demo Channel",
    views: "450K",
    timeAgo: "3 months ago",
  },
  {
    id: 3,
    videoUrl: "https://res.cloudinary.com/drrj8rl9n/video/upload/v1757175304/Rim_Jhim_-_Khan_Saab_ft._Pav_Dharia_PunjabiSong_Fresh_Media_Records_p1ugsf.mp4",
    thumbnailUrl: "https://res.cloudinary.com/drrj8rl9n/image/upload/v1755250102/cld-sample-4.jpg",
    avatar: "https://randomuser.me/api/portraits/men/77.jpg",
    title: "Cute Dog Video Compilation",
    channelName: "Animal Planet",
    views: "1.1M",
    timeAgo: "2 weeks ago",
  }
];
